server.port=9000

spring.application.name=spring-7-auth-server

# Enable ANSI colors in console output
spring.output.ansi.enabled=always

# security logging
logging.level.org.springframework.security=trace


